#!/bin/bash
# A simple script to bootstrap a new computer machine-orama
# Rory Jacob - 12/April/2019

echo "
__  ___.                  __            __                        
_______  ___________ ___.__.   |__| \_ |__   ____   _____/  |_  _______/  |_____________  ______  
\_  __ \/  _ \_  __ <   |  |   |  |  | __ \ /  _ \ /  _ \   __\/  ___/\   __\_  __ \__  \ \____ \ 
|  | \(  <_> )  | \/\___  |   |  |  | \_\ (  <_> |  <_> )  |  \___ \  |  |  |  | \// __ \|  |_> >
|__|   \____/|__|   / ____/\__|  |  |___  /\____/ \____/|__| /____  > |__|  |__|  (____  /   __/ 
\/    \______|      \/                        \/                   \/|__|    
"

usage()
{
    echo "usage: bootstrap-computer --home ~/test/ --dotfiles

    --all               Install everything. The whole mishpacha
    --programs          Install programs
    --dotfiles          Install the dotfiles
    --home              The home directory to install the dot files (defaults to ~/) 
    "
}
validate_and_prompt() {

    local all=$1
    local dotfiles=$2
    local programs=$3
    local home=$4

    local output=""
    if [[ ${all} == true ]]; then
        output="Installing everything. Daaaaaaamn."
    else
        if [[ ${dotfiles} == true ]]; then
            output="Installing dotfiles to ${home}\n"
        fi

        if [[ ${programs} == true ]]; then
            output="${output}Installing programs"
        fi

        if [[ ${output} == "" ]]; then
            usage
            exit 1
        fi

    fi

    echo -e "${output}"

    echo "Are you sure? (y/N)"

    read continue

    if [[ ${continue} == "y" ]]; then
        return 1
    else
        exit 0
    fi
}

# parsing the cmd
install_directory=$HOME
install_everything=false
install_dotfiles=false
install_programs=false
while [[ "$1" != "" ]]; do
    case $1 in
        --all )
            install_everything=true
            ;;
        --dotfiles )
            install_dotfiles=true
            ;;
        --programs )
            install_programs=true
            ;;
        --home )    shift
            install_directory=$1
            ;;
        * )                     
            usage
            exit 1
    esac
    shift
done

validate_and_prompt $install_everything $install_dotfiles $install_programs $install_directory

echo "Let's get it started"

packages_to_install=('git' 'ripgrep' 'go' 'tldr' 'awscli' 'tmux' 'vim' 'python3' 'pandoc' 'coreutils')

echo "Installing OS specific packages"

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Mac OS detected"

    if [[ ${install_everything} == true ]]; then
        # install xcode basics
        echo "Installing xcode basics. Gotta get those basics"
        xcode-select --install

        # install brew for dope package managing
        echo "Get that sweet sweet brew. A saviour to mac package management"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if [[ (${install_everything} == true) || (${install_programs} == true) ]]; then
        # make sure it is all setup and working
        echo "Making sure everything is hunky dory with brew. Stay safe out there"
        brew doctor

        for package in "${packages_to_install[@]}"
        do
            echo "Installing ${package}"
            brew install "${package}"
        done
    else
        echo "Skipping package installation"
    fi
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo "Linux detected"

    if [[ (${install_everything} == true) || (${install_programs} == true) ]]; then
        # first make sure you are up to date with the apt lists
        sudo apt update

        # and then lets go and get everything up to date
        apt list --upgradable
        sudo apt upgrade

        # install all the packages, the linux way ;)
        for package in "${packages_to_install[@]}"
        do
            echo "Installing ${package}"

            if [[ "${package}" == "go" ]]; then
                OS=linux
                ARCH=amd64
                VERSION=12.5
                wget go-install.tar.gz "https://dl.google.com/go/go1.${VERSION}.${OS}-${ARCH}.tar.gz"
                tar -C /usr/local -xzf go-install.tar.gz

                rm go-install.tar.gz
            elif [[ "${package}" == "tldr" ]]; then
                mkdir -p ~/bin
                curl -o ~/bin/tldr https://raw.githubusercontent.com/raylee/tldr/master/tldr
                chmod +x ~/bin/tldr
            else
                yes | sudo apt-get install "${package}"
            fi
        done
    fi
fi

if [[ (${install_everything} == true) || (${install_programs} == true) ]]; then
    echo "Installing goodies for all OS'"

    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    if [ -d "~/.emacs.d" ]; then
        echo "Skipping installation of spacemacs since it is already there"
    else
        echo "Installing spacemacs #killing it"
        git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    fi

    if [ -f "~/.vim/bundle/Vundle.vim" ]; then
        echo "Skipping installation of vundle since it is already there"
    else
        echo "Installing vundle for vim package management"
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    fi
fi

echo "Done installing packages"

if [[ (${install_everything} == true) || (${install_dotfiles} == true) ]]; then
    install_directory=`realpath $install_directory`

    echo "Using home directory: $install_directory"

    echo "Installing dotfiles"

    mkdir /tmp/bootstrap
    git clone https://github.com/roryj/bootstrap /tmp/bootstrap

    rsync -av --exclude '*.git*' --exclude '*Config' --exclude '*README.md' --exclude '*bootstrap-computer'  /tmp/bootstrap/ $install_directory

    echo "dotfiles installed to ${install_directory}"

    vim +PluginInstall +qall
    source ~/.zshrc

    rm -rf /tmp/bootstrap
else
    echo "Skipping dotfile installation"
fi

echo "Goodbye"
