#!/bin/bash
# A simple script to bootstrap a new computer machine-orama
# Rory Jacob - 12/April/2019

echo "
__  ___.                  __            __                        
_______  ___________ ___.__.   |__| \_ |__   ____   _____/  |_  _______/  |_____________  ______  
\_  __ \/  _ \_  __ <   |  |   |  |  | __ \ /  _ \ /  _ \   __\/  ___/\   __\_  __ \__  \ \____ \ 
|  | \(  <_> )  | \/\___  |   |  |  | \_\ (  <_> |  <_> )  |  \___ \  |  |  |  | \// __ \|  |_> >
|__|   \____/|__|   / ____/\__|  |  |___  /\____/ \____/|__| /____  > |__|  |__|  (____  /   __/ 
\/    \______|      \/                        \/                   \/|__|    
"

sleep 1.5

# parsing the cmd
install_directory=$HOME

usage()
{
    echo "usage: bootstrap-laptop --home ~/test/

    --home   The home directory to install the dot files (defaults to ~/) 
    "
}


while [[ "$1" != "" ]]; do
    case $1 in
        --home )      shift
            install_directory=$1
            ;;
        * )                     
            usage
            exit 1
    esac
    shift
done


install_directory=`pwd $install_directory`

# Configuration
echo "Using home directory: $install_directory"

echo "Getting started..."

echo "Installing dotfiles"

all_dotfiles=`ls | find . -name '.*' -not -name '.git*' -not -name '.' | cut -d '/' -f2`

echo "all dotfiles:"
echo "$all_dotfiles"

for dotfile in ${all_dotfiles};
do
    echo "installing $dotfile to $HOME_DIRECTORY"
    cp "./$dotfile" $HOME_DIRECTORY
done

echo "Installing standalone programs"

packages_to_install=('ripgrep' 'go' 'tldr' 'awscli' 'tmux' 'vim' 'python3')

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Mac OS detected"

    # install xcode basics
    #xcode-select --install

    # install brew for dope package managing
    #/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # make sure it is all setup and working
    #brew doctor

    # now get a bunch of packages that are useful
    for package in "${packages_to_install[@]}" 
    do
        echo "Installing ${package}"
        #brew install "${package}"
    done
fi

